const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const els=new Map();function el(id){if(!els.has(id))els.set(id,{textContent:'',value:'AT',className:'',disabled:false,style:{},dataset:{},classList:{toggle(){}},addEventListener(type,fn){this[type]=fn},setAttribute(key,value){this[key]=value},click(){},scrollTop:0,scrollHeight:1});return els.get(id)}
const pduFixture='00040B912143658709F100006201702143650005C8329BFD06';
let simIdentity='001010000000001',smsMode=0,smsStore='SM',cnmi='0,0,0,0,0',smsPdu=pduFixture,smsDeleted=false,smsInput=false,smsPayload='',smsFailure=false,ussdFailure=false,confirmDelete=true;
let responses=[],receive,pendingBytes=0,claimed=false,opened=false,tools=[],writes=[];
const feed=s=>{const v={status:'ok',data:new DataView(new TextEncoder().encode(s).buffer)};if(receive){const r=receive;receive=null;r(v)}else responses.push(v)};
const modem={configuration:{interfaces:[{interfaceNumber:2,alternates:[{endpoints:[{direction:'out',endpointNumber:3},{direction:'in',endpointNumber:4}]}]}]},get opened(){return opened},async open(){opened=true},async claimInterface(n){assert.equal(n,2);claimed=true},async releaseInterface(){claimed=false},async close(){opened=false;if(receive){const r=receive;receive=null;r({status:'ok'})}},async transferIn(ep){assert.equal(ep,4);if(responses.length)return responses.shift();return new Promise(r=>receive=r)},async transferOut(ep,data){assert.equal(ep,3);if(smsInput){if(data[0]===27){smsInput=false;feed('\r\nOK\r\n');}else if(data[0]===26){smsInput=false;feed(smsFailure?'\r\n+CMS ERROR: 500\r\n':'\r\n+CMGS: 7\r\nOK\r\n');}else smsPayload+=new TextDecoder().decode(data);return {status:'ok',bytesWritten:data.length}}if(pendingBytes){pendingBytes-=data.length;if(pendingBytes===0)feed('\r\nOK\r\n');return {status:'ok',bytesWritten:data.length}}const cmd=new TextDecoder().decode(data).trim();writes.push(cmd);let answer='';if(/^AT\+CMGS=/.test(cmd)){smsInput=true;smsPayload='';feed('\r\n> ');return {status:'ok',bytesWritten:data.length}}if(/^AT\+CMGF=[01]$/.test(cmd))smsMode=Number(cmd.at(-1));if(/^AT\+CPMS="/.test(cmd))smsStore=cmd.match(/"([A-Z]+)"/)[1];if(/^AT\+CNMI=/.test(cmd))cnmi=cmd.split('=')[1];if(cmd==='AT+CUSD=1,"*100#",15'){feed(ussdFailure?'\r\n+CMS ERROR: 500\r\n':'\r\nOK\r\n+CUSD: 1,"Balance: 12.50\r\n1. More",15\r\n');return {status:'ok',bytesWritten:data.length}}switch(cmd){case 'AT+CSCS?':answer='+CSCS: "IRA"';break;case 'AT+CIMI':answer=simIdentity;break;case 'AT+CNMI?':answer='+CNMI: '+cnmi;break;case 'AT+CMGF?':answer='+CMGF: '+smsMode;break;case 'AT+CPMS?':answer='+CPMS: "'+smsStore+'",1,20,"SM",1,20,"SM",1,20';break;case 'AT+CMGL=4':answer=smsDeleted?'':'+CMGL: 0,0,,24\r\n'+smsPdu;break;case 'AT+CMGR=0':answer='+CMGR: 1,,24\r\n'+smsPdu;break;case 'AT+CMGD=0,0':smsDeleted=true;break;case 'AT+CGPSINFOCFG?':answer='+CGPSINFOCFG: 0,0';break;case 'ATI':answer='Model: SIMCOM_SIM7600G\r\nRevision: TEST';break;case 'AT+CPIN?':answer='+CPIN: READY';break;case 'AT+COPS?':answer='+COPS: 0,0,"TEST",7';break;case 'AT+CEREG?':answer='+CEREG: 0,1';break;case 'AT+CGATT?':answer='+CGATT: 1';break;case 'AT+CSQ':answer='+CSQ: 20,99';break;case 'AT+CPSI?':answer='+CPSI: LTE,Online,001-01,0x0001,1234567,123,EUTRAN-BAND1,300,4,4,-135,-1126,-802,8';break;case 'AT+CGPADDR':answer='+CGPADDR: 1,10.64.0.25';break;case 'AT+HTTPDATA=150001,10000':pendingBytes=150001;feed('\r\nDOWNLOAD\r\n');return {status:'ok',bytesWritten:data.length};case 'AT+HTTPACTION=0':answer='+HTTPACTION: 0,200,1000000';break;case 'AT+HTTPACTION=1':answer='+HTTPACTION: 1,200,0';break;}feed(`\r\n${answer}\r\nOK\r\n`);return {status:'ok',bytesWritten:data.length}}};
const timers=[];const document={getElementById:el,querySelectorAll(){return []},createElement(){return el('a')},modelContext:{registerTool(t){tools.push(t)}}};const ctx=vm.createContext({document,navigator:{usb:{async requestDevice(){return modem},addEventListener(){}}},TextEncoder,TextDecoder,Uint8Array,DataView,Date,Math,Promise,Error,setTimeout,clearTimeout,setInterval(fn){timers.push(fn);return timers.length},clearInterval(){},performance,Blob,URL,console,window:{confirm(){return confirmDelete}}});
vm.runInContext(fs.readFileSync(process.argv[2],'utf8'),ctx);const run=s=>vm.runInContext(s,ctx);
(async()=>{await run('connect()');assert.equal(el('sim').textContent,'READY');assert.equal(el('operator').textContent,'TEST');assert.equal(el('rsrp').textContent,'-112.6');assert.equal(el('rsrq').textContent,'-13.5');assert.equal(el('rssi').textContent,'-80.2');assert.equal(el('registration').textContent,'Registered · home');assert.equal(el('ip').textContent,'10.64.0.25');assert(claimed);await assert.rejects(run('send("AT\\rBAD")'),/single AT/);run('parseGnss("+CGPS: 1,1\\n+CGNSSINFO: 3,08,04,02,5128.614000,N,00000.030000,W,061026,163000.0,45.0,10.0,123.0,1.5,1.0,1.1")');assert.equal(el('latitude').textContent,'51.47690000°');assert.equal(el('longitude').textContent,'-0.00050000°');assert.equal(el('gnssfix').textContent,'3D fix');assert.equal(el('groundspeed').textContent,'18.5 km/h · 10.0 kn');assert.equal(el('gpssats').textContent,8);assert.equal(el('dops').textContent,'1.5 / 1.0 / 1.1');assert(Math.abs(run('gnssCoordinate("3426.693019","S",true)')+34.44488365)<1e-7);assert.equal(run('gnssCoordinate("5360.000","N",true)'),null);assert.equal(run('gnssCoordinate("","N",true)'),null);run('parseGnss("+CGNSSINFO: ,,,,,,,,,,,,,,,")');assert.equal(el('latitude').textContent,'—');assert.equal(el('gnssfix').textContent,'Searching · no fix');assert.equal(tools[0].execute({}).gnss.fix,false);run('parseGnss("+CGPS: 0,1")');assert.equal(el('gnssfix').textContent,'Receiver off');assert(writes.includes('AT+CGPSINFOCFG=1,198143'));run('demoNmea()');assert.equal(el('inview').textContent,'10 IN VIEW');assert(el('satellites').innerHTML.includes('circle'));assert(el('spectrum').innerHTML.includes('signalbar'));const checksumSentence=body=>{let x=0;for(const c of body)x^=c.charCodeAt(0);return '$'+body+'*'+x.toString(16).padStart(2,'0').toUpperCase()};ctx.nmeaTest=checksumSentence('GPGSV,2,1,05,01,45,100,30,02,60,200,35,03,20,300,25,04,30,050,40');run('parseNmea(nmeaTest)');assert.equal(el('inview').textContent,'10 IN VIEW');ctx.nmeaTest=checksumSentence('GPGSV,2,2,05,05,70,020,48');run('parseNmea(nmeaTest)');assert.equal(el('inview').textContent,'11 IN VIEW');assert.equal(run('parseNmea("$GPGSV,1,1,00*00")'),false);ctx.nmeaTest=checksumSentence('GPGSV,1,1,00');run('parseNmea(nmeaTest)');assert.equal(el('inview').textContent,'6 IN VIEW');assert.equal(run('satelliteSystem("GN",72)'), 'GLONASS');assert.equal(run('satelliteSystem("GA",12)'), 'Galileo');run('for(const sat of nmea.satellites.values())sat.time=0;drawSatellites()');assert.equal(el('inview').textContent,'0 IN VIEW');await run('speedtest()');assert.equal(writes.filter(x=>x==='AT+HTTPACTION=0').length,3);assert.equal(writes.filter(x=>x==='AT+HTTPACTION=1').length,3);assert(el('speedstatus').textContent.startsWith('Complete'));assert.equal(pendingBytes,0);assert.equal(writes.at(-1),'AT+HTTPTERM');assert.equal(tools.length,1);const status=tools[0].execute({});assert.equal(status.connected,true);assert.throws(()=>tools[0].execute({bad:true}),/empty object/);
assert.equal(run('gsmAlphabet.length'),128);
ctx.fixture=pduFixture;
assert.equal(run('decodeSmsPdu(fixture).text'),'Hello');
assert.equal(run('decodeSmsPdu(fixture).address'),'+12345678901');
assert.equal(run('decodeSmsPdu(fixture).timestamp'),'2026-10-07 12:34:56 UTC+00:00');
assert.equal(run('decodeSmsPdu(buildSmsPdu("+12345678901","Hello ^ €").hex).text'),'Hello ^ €');
assert.equal(run('decodeSmsPdu(buildSmsPdu("+12345678901","Zażółć").hex).text'),'Zażółć');
assert.equal(run('smsEncoding("x".repeat(160)).valid'),true);
assert.equal(run('smsEncoding("x".repeat(161)).valid'),false);
assert.equal(run('smsEncoding("ż".repeat(71)).valid'),false);
assert.equal(run('smsEncoding("😀").valid'),false);
assert.throws(()=>run('buildSmsPdu("+1\\rAT", "test")'),/phone number/);
assert.throws(()=>run('decodeSmsPdu("0004")'),/Truncated/);
// Multipart UCS2 header: 8-bit reference 42, part 1 of 2.
ctx.multipart='00440B912143658709F10008620170214365000A0500032A020100480069';
assert.equal(run('decodeSmsPdu(multipart).text'),'Hi');
assert.equal(run('decodeSmsPdu(multipart).concat.part'),1);
// HTML, command-looking lines and Unicode stay message content.
el('smsstore').value='SM';await run('loadMessages()');
assert.equal(run('sms.messages.length'),1);assert.equal(run('sms.messages[0].index'),0);
assert.equal(smsMode,0);assert.equal(smsStore,'SM');
assert(el('smslist').innerHTML.includes('Hello'));
run('sms.messages[0].text="<script>bad</script>\\nOK\\n+CUSD: 1";renderSms()');
assert(!el('smslist').innerHTML.includes('<script>'));assert(el('smslist').innerHTML.includes('&lt;script&gt;'));
// Receive notification interleaved with command responses, including slot zero.
ctx.incomingFixture='+CMTI: "SM",0\r\n';run("consume(incomingFixture)");assert.equal(el("smsbadge").textContent,"NEW TEXT");
el('ussdcode').value='*100#';await run('runUssd()');
assert.equal(el('ussdresult').textContent,'Balance: 12.50\n1. More');assert.equal(run('ussd.active'),true);
ctx.ussdFixture='+CUSD: 0,"005A0061017C00F301420107",72';run("handleUssd(ussdFixture)");assert.equal(el('ussdresult').textContent,'Zażółć');
await run('runUssd(true)');assert(writes.includes('AT+CUSD=2'));assert.equal(run('ussd.active'),false);
ussdFailure=true;await assert.rejects(run('runUssd()'),/CMS ERROR/);ussdFailure=false;
assert.equal(run('state.busy'),false);assert.equal(run('ussd.pending'),false);
el('smsnumber').value='+12345678901';el('smsbody').value='Hello';await run('sendSms()');
ctx.sent=smsPayload;assert.equal(run('decodeSmsPdu(sent).text'),'Hello');assert(!smsInput);assert.equal(smsMode,0);
assert(el('smssendstatus').textContent.includes('Accepted by the network'));
smsFailure=true;await assert.rejects(run('sendSms()'),/CMS ERROR/);smsFailure=false;assert.equal(run('state.busy'),false);assert.equal(smsMode,0);
// Stale slot fingerprints and cancelled confirmations cannot delete a different text.
await run('loadMessages()');confirmDelete=false;await run('deleteMessage(0)');assert(!smsDeleted);
confirmDelete=true;smsPdu=pduFixture.slice(0,-2)+'07';await assert.rejects(run('deleteMessage(0)'),/slot has changed/);assert(!smsDeleted);
smsPdu=pduFixture;await run('loadMessages()');simIdentity='001010000000002';await assert.rejects(run('deleteMessage(0)'),/SIM changed/);assert(!smsDeleted);assert.equal(run('sms.messages.length'),0);
await run('loadMessages()');await run('deleteMessage(0)');assert(smsDeleted);assert.equal(run('sms.messages.length'),0);
await run('disconnect()');assert(!claimed);assert.equal(cnmi,'0,0,0,0,0');
run('demo()');assert.equal(el('connection').textContent,'Demo · simulated');assert.equal(tools[0].execute({}).simulated,true);run('demo()');assert.equal(el('operator').textContent,'—');console.log('PASS: USB endpoint selection, AT response parsing, metrics, invalid command rejection, download and upload sequence, cleanup, disconnect, demo, GNSS units, hemisphere conversion, invalid coordinates, fix loss, NMEA checksum, multipart GSV assembly, satellite expiry and structured read-back. SMS GSM/Unicode PDU encoding and decoding, multipart headers, prompt without newline, send errors, USSD menus and Unicode, incoming notifications, storage restoration, safe deletion and SIM changes. Browser hardware access remains unverified.');})().catch(e=>{console.error(e);process.exitCode=1});
