/* Copyright (c) 2026 Piotr Godlewski. SPDX-License-Identifier: MIT */
const $ = id => document.getElementById(id);
const encoder = new TextEncoder();
const state = { connected:false, demo:false, busy:false, samples:[], values:{}, log:[], updated:null, gnss:{power:null,fix:false,lat:null,lon:null,updated:null} };
const sms={messages:[],loaded:false,pending:false,dirty:new Set(),identity:null,previousCnmi:null,receiving:false};
const ussd={active:false,pending:false,timeout:null,resolve:null,buffer:''};
let device, reader, waiter, partial='', timer, session=0, pollPending=false, queue=Promise.resolve();
const set = (id,value) => { $(id).textContent = value ?? '—'; };
function notice(message,error=false){ $('notice').textContent=message; $('notice').classList.toggle('error',error); }
function log(message){ const line=`${new Date().toLocaleTimeString()}  ${message}`; state.log.push(line); if(state.log.length>800)state.log.shift(); $('terminal').textContent=state.log.join('\n'); $('terminal').scrollTop=$('terminal').scrollHeight; }
function controls(){ $('connection').textContent=state.demo?'Demo · simulated':state.connected?'USB connected':'Disconnected'; $('connection').className='pill'+(state.demo?' demo':state.connected?' live':''); $('connect').textContent=state.connected?'Disconnect':'Connect USB'; $('connect').disabled=state.busy; $('demo').textContent=state.demo?'Exit demo':'Try demo'; $('demo').disabled=state.connected||state.busy; for(const el of document.querySelectorAll('[data-command],#command,#send,#refresh,#speedtest,#gnsstoggle'))el.disabled=!state.connected||state.busy; for(const el of document.querySelectorAll('[data-sms-control],[data-sms-delete]'))el.disabled=!state.connected||state.busy;updateSmsCount();$('gnsstoggle').textContent=state.gnss.power===true?'Disable GNSS':'Enable GNSS';$('copycoords').disabled=!state.gnss.fix||(!state.connected&&!state.demo);$('openmap').disabled=$('copycoords').disabled; }
function reset(){clearMessaging();resetNmea();state.gnss={power:null,fix:false,lat:null,lon:null,updated:null};clearGnss('Waiting for modem');set('gnsspower','UNKNOWN');set('gnssupdated','No position reading yet');set('gnsshint','Connect USB to read the satellite receiver.');state.values={};state.samples=[];state.updated=null;for(const id of ['operator','radio','band','sim','rsrp','rsrq','rssi','sinr','csq','plmn','cell','tac','pci','earfcn','ip','firmware','model','download','upload'])set(id,'—');set('registration','Waiting for modem');set('attached','Data attachment unknown');set('signalquality','No measurement yet');set('lastupdate','No readings yet');draw();}
function draw(){const pts=state.samples.slice(-90).map((s,i,a)=>[52+i*728/Math.max(a.length-1,1),25+(Math.min(-70,Math.max(-130,s.rsrp))+70)*-165/60]);$('line').setAttribute('d',pts.map(([x,y],i)=>`${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`).join(' '));$('area').setAttribute('d',pts.length?`M${pts[0][0]},190 ${pts.map(([x,y])=>`L${x},${y}`).join(' ')} L${pts.at(-1)[0]},190Z`:'');$('chartempty').style.display=pts.length?'none':'';}
function parse(text){
 let m;
 parseGnss(text);
 if((m=text.match(/Model:\s*([^\r\n]+)/)))set('model',m[1]);
 if((m=text.match(/Revision:\s*([^\r\n]+)/)))set('firmware',m[1]);
 if((m=text.match(/\+CPIN:\s*([^\r\n]+)/)))set('sim',m[1]);
 if(/SIM not inserted/i.test(text))set('sim','Not detected');
 if((m=text.match(/\+COPS:\s*\d+,\d+,"([^"]*)"(?:,(\d+))?/)))set('operator',m[1]);
 if((m=text.match(/\+CEREG:\s*(?:\d+,)?(\d+)/))){const names=['Not registered','Registered · home','Searching','Registration denied','Unknown','Registered · roaming'];set('registration',names[Number(m[1])]||'Unknown');}
 if((m=text.match(/\+CGATT:\s*(\d)/)))set('attached',m[1]==='1'?'Mobile data attached':'Mobile data detached');
 if((m=text.match(/\+CSQ:\s*(\d+),(\d+)/)))set('csq',m[1]==='99'?'Unknown':m[1]);
 if((m=text.match(/\+CGPADDR:\s*1,\s*"?([^"\r\n,]+)/)))set('ip',m[1]);
 if((m=text.match(/\+CPSI:\s*([^\r\n]+)/))){const p=m[1].split(',').map(x=>x.trim());set('radio',p[0]);if(p[0]==='LTE'&&p.length>=14){set('band',p[6].replace('EUTRAN-',''));for(const [id,index] of [['plmn',2],['tac',3],['cell',4],['pci',5],['earfcn',7]])set(id,p[index]);const rsrp=Number(p[11])/10;set('rsrq',(Number(p[10])/10).toFixed(1));set('rsrp',rsrp.toFixed(1));set('rssi',(Number(p[12])/10).toFixed(1));set('sinr',p[13]);set('signalquality',rsrp>=-90?'Strong signal':rsrp>=-105?'Moderate signal':'Weak signal');if(Number.isFinite(rsrp)){state.samples.push({time:Date.now(),rsrp});if(state.samples.length>90)state.samples.shift();draw();}}else{set('band',p[1]||'No service');for(const id of ['rsrp','rsrq','rssi','sinr','plmn','tac','cell','pci','earfcn'])set(id,'—');set('signalquality','No LTE measurement');}}
 state.updated=Date.now();set('lastupdate',`Updated ${new Date(state.updated).toLocaleTimeString()} · polling every 5 s`);
}
function gnssCoordinate(raw,hemisphere,latitude){
 if(!raw||!new RegExp(latitude?'^[NS]$':'^[EW]$').test(hemisphere)||!/^\d+(?:\.\d+)?$/.test(raw))return null;
 const n=Number(raw),degrees=Math.floor(n/100),minutes=n-degrees*100,limit=latitude?90:180;
 if(minutes>=60||degrees>limit||(degrees===limit&&minutes!==0))return null;
 return (degrees+minutes/60)*(/[SW]/.test(hemisphere)?-1:1);
}
function clearGnss(label){state.gnss.fix=false;state.gnss.lat=null;state.gnss.lon=null;for(const id of ['latitude','longitude','altitude','groundspeed','course','gnssutc','dops','gpssats','glosats','bdsats','fixquality','geoid','ellipsoid'])set(id,'—');set('positionerror','Not reported by this modem');updateCourse();set('gnssfix',label);controls();}
function fixUtc(date,time){if(!/^\d{6}$/.test(date)||!/^\d{6}(?:\.\d+)?$/.test(time))return '—';return `20${date.slice(4,6)}-${date.slice(2,4)}-${date.slice(0,2)} ${time.slice(0,2)}:${time.slice(2,4)}:${time.slice(4)} UTC`;}
function parseGnss(text){let m;
 if((m=text.match(/\+CGPS:\s*([01])(?:,|$)/m))){state.gnss.power=m[1]==='1';set('gnsspower',state.gnss.power?'ON':'OFF');if(!state.gnss.power){clearGnss('Receiver off');set('gnsshint','Enable GNSS to start receiving satellites.');}else if(!state.gnss.fix){set('gnssfix','Searching for satellites');set('gnsshint','Keep the antenna outside or near a window with a clear view of the sky.');}controls();}
 if((m=text.match(/\+CGNSSINFO:\s*([^\r\n]*)/))){const p=m[1].split(',').map(x=>x.trim());state.gnss.updated=Date.now();set('gnssupdated',`Position checked ${new Date().toLocaleTimeString()}`);const lat=gnssCoordinate(p[4],p[5],true),lon=gnssCoordinate(p[6],p[7],false);
 if(!['2','3'].includes(p[0])||lat===null||lon===null||state.gnss.power===false){clearGnss(state.gnss.power===false?'Receiver off':'Searching · no fix');set('gnsshint',state.gnss.power===false?'Enable GNSS to start receiving satellites.':'No valid position yet. A first fix can take several minutes with a clear view of the sky.');return;}
 state.gnss.fix=true;state.gnss.lat=lat;state.gnss.lon=lon;set('gnssfix',`${p[0]}D fix${state.demo?' · simulated':''}`);set('latitude',lat.toFixed(8)+'°');set('longitude',lon.toFixed(8)+'°');set('gnsshint','Coordinates are from the modem’s satellite receiver.');
 const measurement=(raw,unit,factor=1)=>raw!==undefined&&raw!==''&&Number.isFinite(Number(raw))?(Number(raw)*factor).toFixed(1)+unit:'—';set('altitude',measurement(p[10],' m'));set('groundspeed',p[11]!==''&&Number.isFinite(Number(p[11]))?measurement(p[11],' km/h',1.852)+' · '+measurement(p[11],' kn'):'—');set('course',measurement(p[12],'°'));set('gnssutc',fixUtc(p[8],p[9]));set('dops',[p[13],p[14],p[15]].map(x=>x||'—').join(' / '));for(const [id,index] of [['gpssats',1],['glosats',2],['bdsats',3]])set(id,/^\d+$/.test(p[index]||'')?Number(p[index]):'—');updateCourse();controls();}
}
async function toggleGnss(){if(!state.connected||state.busy)return;state.busy=true;controls();try{await enqueue(async()=>{await command(state.gnss.power===true?'AT+CGPS=0':'AT+CGPS=1');parse(await command('AT+CGPS?'));if(state.gnss.power)parse(await command('AT+CGNSSINFO'));});}finally{state.busy=false;controls();}}
function rejectWait(error){if(waiter){clearTimeout(waiter.timeout);const w=waiter;waiter=null;w.reject(error);}}
function consume(chunk){partial+=chunk;const lines=partial.split(/\r\n|\r|\n/);partial=lines.pop();for(const raw of lines){const line=raw.trim();if(!line)continue;log(line);if(line.startsWith('$')){parseNmea(line);continue;}if(incomingMessage(line))continue;if(waiter){waiter.lines.push(line);if(/^(ERROR|\+CME ERROR:|\+CMS ERROR:)/.test(line)){rejectWait(new Error(line));continue;}if(waiter.matches(line)){clearTimeout(waiter.timeout);const w=waiter;waiter=null;w.resolve(w.lines.join('\n'));}}}if(waiter&&/^\s*>\s*$/.test(partial)&&waiter.matches('>')){partial='';const w=waiter;clearTimeout(w.timeout);waiter=null;w.resolve(w.lines.join('\n')+'\n>');}}
async function readLoop(dev,key){const decoder=new TextDecoder();try{while(state.connected&&session===key){const r=await dev.transferIn(4,4096);if(r.status!=='ok')throw new Error(`USB read: ${r.status}`);if(r.data)consume(decoder.decode(r.data,{stream:true}));}}catch(error){if(state.connected&&session===key){notice(`USB connection lost: ${error.message}. Reconnect the modem.`,true);await disconnect(false);}}}
function awaitResponse(matches,timeout=6000){if(waiter)throw new Error('Another modem response is pending');return new Promise((resolve,reject)=>{waiter={matches,resolve,reject,lines:[],timeout:setTimeout(()=>rejectWait(new Error('Modem response timed out. Disconnect and reconnect before retrying.')),timeout)};});}
async function write(bytes){const r=await device.transferOut(3,bytes);if(r.status!=='ok'||r.bytesWritten!==bytes.byteLength)throw new Error('USB write did not complete');}
async function command(text,matches=line=>line==='OK',timeout=6000){if(!state.connected)throw new Error('Connect the modem first');log(`› ${text}`);const response=awaitResponse(matches,timeout);try{await write(encoder.encode(text+'\r'));}catch(e){rejectWait(e);}return response;}
function enqueue(fn){const job=queue.then(fn);queue=job.catch(()=>{});return job;}
async function connect(){if(state.connected)return disconnect();if(state.busy)return;if(!navigator.usb){notice('WebUSB is unavailable here. Open this page in Google Chrome or Microsoft Edge.',true);return;}state.demo=false;state.busy=true;controls();clearInterval(timer);reset();try{device=await navigator.usb.requestDevice({filters:[{vendorId:0x1e0e,productId:0x9001}]});await device.open();if(!device.configuration)await device.selectConfiguration(1);const iface=device.configuration.interfaces.find(i=>i.interfaceNumber===2);if(!iface||!iface.alternates.some(a=>a.endpoints.some(e=>e.direction==='out'&&e.endpointNumber===3)&&a.endpoints.some(e=>e.direction==='in'&&e.endpointNumber===4)))throw new Error('This modem has an unexpected AT interface layout');await device.claimInterface(2);partial='';state.connected=true;session++;reader=readLoop(device,session);controls();notice('Connected directly to the modem over USB. Reading SIM and LTE status…');await enqueue(async()=>{await command('AT');await command('ATE0');await setupNmea();await setupMessaging();parse(await command('ATI'));await poll();});state.busy=false;controls();notice('Live modem connection. Data tests use your SIM’s mobile data allowance; ordinary browser traffic uses the computer’s connection.');timer=setInterval(()=>{if(state.connected&&!state.busy&&!pollPending){pollPending=true;enqueue(poll).catch(report).finally(()=>{pollPending=false;});}},5000);}catch(e){notice(e.name==='NotFoundError'?'No modem selected. Click Connect USB to try again.':`Could not connect: ${e.message}`,true);if(state.connected)await disconnect(false);else if(device?.opened)await device.close().catch(()=>{});state.busy=false;controls();}}
async function disconnect(restore=true){clearInterval(timer);if(ussd.pending){clearTimeout(ussd.timeout);ussd.pending=false;ussd.resolve?.();}if(restore&&state.connected&&!waiter&&sms.previousCnmi)await command(`AT+CNMI=${sms.previousCnmi.join(',')}`).catch(()=>{});sms.previousCnmi=null;sms.receiving=false;sms.identity=null;if(restore&&state.connected&&!waiter&&nmea.active&&nmea.previous)await command(`AT+CGPSINFOCFG=${nmea.previous.join(',')}`).catch(()=>{});nmea.active=false;nmea.previous=null;set('nmeastatus','Disconnected · satellite observations are stale');if(restore&&state.connected&&!waiter)await command('ATE1').catch(()=>{});state.connected=false;session++;rejectWait(new Error('USB disconnected'));const old=device;device=null;try{if(old?.opened){await old.releaseInterface(2).catch(()=>{});await old.close();}}catch{}state.busy=false;controls();if(state.gnss.fix)set('gnssfix','Last fix · disconnected');set('gnssupdated','Disconnected · readings are stale');set('smsstatus','Disconnected · displayed messages are stale. Reconnect and load messages before deleting.');set('ussdstatus','Disconnected · last response is stale.');log('USB disconnected');if(restore)notice('Disconnected. Last readings remain visible.');}
async function poll(){drawSatellites();if(sms.identity){try{await checkSmsSim();}catch(e){log('SIM check: '+e.message);}}for(const q of ['AT+CPIN?','AT+COPS?','AT+CEREG?','AT+CGATT?','AT+CSQ','AT+CPSI?','AT+CGPADDR','AT+CGPS?','AT+CGNSSINFO']){if(!state.connected)return;if(q==='AT+CGNSSINFO'&&state.gnss.power===false)continue;try{parse(await command(q));}catch(e){if(/timed out|disconnect/i.test(e.message))throw e;log(`Query unavailable: ${q}`);if(q==='AT+CPIN?'&&/SIM not inserted/i.test(e.message)){set('sim','Not detected');set('operator','—');set('registration','SIM unavailable');set('attached','Mobile data unavailable');}}}if(sms.loaded&&sms.dirty.has($('smsstore').value)&&$('smsauto').checked)setTimeout(()=>loadMessages().catch(report),0);}
function report(error){notice(error.message,true);if(/timed out/.test(error.message)&&state.connected&&!state.busy)disconnect(false);}
async function send(text){text=text.trim();if(!/^AT/i.test(text)||/[\r\n]/.test(text)||text.length>512)throw new Error('Enter a single AT command of up to 512 characters');state.busy=true;controls();try{await enqueue(async()=>parse(await command(text)));}finally{state.busy=false;controls();}}
async function speedtest(){state.busy=true;controls();const downloads=[],uploads=[];let http=false,inputPending=false;set('download','—');set('upload','—');const startAll=performance.now();try{await enqueue(async()=>{
 await command('AT+HTTPINIT',undefined,15000);http=true;
 for(let n=0;n<3;n++){set('speedstatus',`Download ${n+1} / 3 · 1 MB`);await command('AT+HTTPPARA="URL","https://speed.cloudflare.com/__down?bytes=1000000"');const start=performance.now();const r=await command('AT+HTTPACTION=0',line=>/^\+HTTPACTION: 0,/.test(line),45000);const seconds=(performance.now()-start)/1000;const match=r.match(/\+HTTPACTION: 0,(\d+),(\d+)/);if(!match||match[1]!=='200'||Number(match[2])!==1000000)throw new Error(`Download failed: ${match?.[1]||r}`);downloads.push(8/seconds);set('download',mean(downloads).toFixed(2));log(`Download ${n+1}: ${(8/seconds).toFixed(2)} Mbps`);}
 await command('AT+HTTPPARA="URL","https://speed.cloudflare.com/__up"');await command('AT+HTTPPARA="CONTENT","application/octet-stream"');
 for(let n=0;n<3;n++){set('speedstatus',`Upload ${n+1} / 3 · 150 kB`);await command('AT+HTTPDATA=150001,10000',line=>line==='DOWNLOAD');inputPending=true;const ready=awaitResponse(line=>line==='OK',15000);try{for(let offset=0;offset<150001;offset+=4095){await write(new Uint8Array(Math.min(4095,150001-offset)).fill(120));await new Promise(r=>setTimeout(r,10));}}catch(e){rejectWait(e);}await ready;inputPending=false;const start=performance.now();const r=await command('AT+HTTPACTION=1',line=>/^\+HTTPACTION: 1,/.test(line),45000);const seconds=(performance.now()-start)/1000;const match=r.match(/\+HTTPACTION: 1,(\d+),(\d+)/);if(!match||match[1]!=='200')throw new Error(`Upload failed: ${match?.[1]||r}`);uploads.push(150001*8/seconds/1e6);set('upload',mean(uploads).toFixed(2));log(`Upload ${n+1}: ${uploads.at(-1).toFixed(2)} Mbps`);}
 });set('speedstatus',`Complete · 3 samples each · ${((performance.now()-startAll)/1000).toFixed(1)} s. Includes HTTP setup overhead.`);
 }catch(e){set('speedstatus',`Test stopped: ${e.message}`);report(e);}finally{if(state.connected){if(inputPending)await write(new Uint8Array([27,13])).catch(()=>{});if(http)await enqueue(()=>command('AT+HTTPTERM',undefined,6000)).catch(e=>log(`Cleanup: ${e.message}`));}state.busy=false;controls();}}
const mean = a => a.reduce((s,n)=>s+n,0)/a.length;
function demo(){if(state.connected)return;clearInterval(timer);state.demo=!state.demo;reset();controls();if(!state.demo){notice('Connect your modem in Chrome or Edge to see live measurements.');return;}notice('Demo mode · all measurements below are simulated. Connect USB for real modem data.');parse('Model: SIMCOM_SIM7600G\nRevision: SIM7600M21-A_V2.0\n+CPIN: READY\n+COPS: 0,0,"TEST",7\n+CEREG: 0,1\n+CGATT: 1\n+CGPADDR: 1,10.64.0.25\n+CSQ: 20,99');for(let n=0;n<40;n++)state.samples.push({time:Date.now()-(40-n)*5000,rsrp:-104+3*Math.sin(n/5)+Math.random()*2});function tick(){parse(`+CPSI: LTE,Online,001-01,0x0001,1234567,123,EUTRAN-BAND1,300,4,4,-135,${Math.round((-104+Math.random()*4)*10)},-802,8`);set('lastupdate','Simulated readings · not connected');}parseGnss('+CGPS: 1,1\n+CGNSSINFO: 3,08,04,02,5128.614000,N,00000.030000,W,061026,163000.0,45.0,0.0,0.0,1.5,1.0,1.1');set('gnsshint','Demo position · simulated coordinates, not your location.');demoNmea();demoMessages();tick();timer=setInterval(()=>{tick();demoNmea();},5000);log('Demo started · simulated data');}
$('openmap').addEventListener('click',()=>{if(state.gnss.fix&&(state.connected||state.demo))window.open(`https://www.google.com/maps?q=${state.gnss.lat},${state.gnss.lon}`,'_blank','noopener,noreferrer');});$('gnsstoggle').addEventListener('click',()=>toggleGnss().catch(report));$('copycoords').addEventListener('click',async()=>{if(!state.gnss.fix)return;try{await navigator.clipboard.writeText(`${state.gnss.lat.toFixed(8)}, ${state.gnss.lon.toFixed(8)}`);notice('Coordinates copied.');}catch{notice('Clipboard access unavailable. Select and copy the displayed coordinates.',true);}});$('connect').addEventListener('click',connect);$('demo').addEventListener('click',demo);$('refresh').addEventListener('click',()=>enqueue(poll).catch(report));$('speedtest').addEventListener('click',speedtest);$('commandform').addEventListener('submit',e=>{e.preventDefault();send($('command').value).catch(report);});document.querySelectorAll('[data-command]').forEach(b=>b.addEventListener('click',()=>send(b.dataset.command).catch(report)));$('clear').addEventListener('click',()=>{state.log=[];$('terminal').textContent='';});$('save').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([state.log.join('\n')],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=`sim7600-${new Date().toISOString().replace(/[:.]/g,'-')}.log`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});navigator.usb?.addEventListener('disconnect',e=>{if(e.device===device){notice('Modem unplugged. Reconnect it and click Connect USB.',true);disconnect(false);}});if(!navigator.usb)notice('This browser does not expose WebUSB. Use Google Chrome or Microsoft Edge for a live connection. Demo mode is available here.',true);
// Structured read-back uses the same visible state; it never initiates a USB permission request.
if(document.modelContext?.registerTool){Promise.resolve(document.modelContext.registerTool({name:'read_lte_dashboard',description:'Read the current displayed LTE status, last update, signal samples and connection mode. No modem commands are sent.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');return {connected:state.connected,simulated:state.demo,updated:state.updated,operator:$('operator').textContent,sim:$('sim').textContent,radio:$('radio').textContent,band:$('band').textContent,rsrp:$('rsrp').textContent,ip:$('ip').textContent,gnss:{...state.gnss},samples:state.samples.slice(-10)};}})).catch(e=>log(`Agent read-back unavailable: ${e.message}`));}

const nmea={satellites:new Map(),cycles:new Map(),used:new Map(),previous:null,active:false,seen:false};
const systemColors={GPS:'#38bdf8',BeiDou:'#fbbf24',Galileo:'#34d399',GLONASS:'#fb7185',QZSS:'#c4b5fd',SBAS:'#94a5b5'};
function satelliteSystem(talker,prn){if(talker==='GL')return 'GLONASS';if(talker==='GA')return 'Galileo';if(talker==='GB'||talker==='BD')return 'BeiDou';if(talker==='GQ'||talker==='PQ')return 'QZSS';if(prn>=193&&prn<=200)return 'QZSS';if(talker==='GN'){if(prn>=65&&prn<=96)return 'GLONASS';if(prn>=201&&prn<=237)return 'BeiDou';if(prn>=301&&prn<=336)return 'Galileo';}return prn>=33&&prn<=64?'SBAS':'GPS';}
function satId(system,prn){return ({GPS:'G',GLONASS:'R',Galileo:'E',BeiDou:'C',QZSS:'J',SBAS:'S'}[system]||'?')+String(prn).padStart(2,'0');}
function skyPoint(el,az){const radius=(90-el)*150/90,angle=az*Math.PI/180;return [220+radius*Math.sin(angle),195-radius*Math.cos(angle)];}
function resetNmea(){nmea.satellites.clear();nmea.cycles.clear();nmea.used.clear();nmea.seen=false;for(const id of ['geoid','ellipsoid','fixquality'])set(id,'—');set('positionerror','Not reported by this modem');set('nmeastatus','NMEA stream starts after USB connection. Systems appear only when reported.');drawSatellites();updateCourse();}
function updateCourse(){const course=Number.parseFloat($('course').textContent),speed=Number.parseFloat($('groundspeed').textContent),available=state.gnss.fix&&Number.isFinite(course)&&Number.isFinite(speed)&&speed>1;set('coursevalue',available?course.toFixed(1)+'°':'—');$('courseneedle').setAttribute('visibility',available?'visible':'hidden');$('courseneedle').setAttribute('transform',`rotate(${available?course:0} 75 75)`);}
function drawSatellites(){const now=Date.now();for(const [key,s] of nmea.satellites)if(now-s.time>15000)nmea.satellites.delete(key);const sats=[...nmea.satellites.values()].sort((a,b)=>(b.cn0??-1)-(a.cn0??-1));set('inview',`${sats.length} IN VIEW`);$('skyempty').style.display=sats.length?'none':'';
 $('satellites').innerHTML=sats.filter(s=>s.el!==null&&s.az!==null).map(s=>{const [x,y]=skyPoint(s.el,s.az);const trail=s.trail.map(([el,az])=>skyPoint(el,az).map(n=>n.toFixed(1)).join(',')).join(' ');const used=[...nmea.used.values()].some(u=>now-u.time<15000&&u.ids.has(s.id));return `<polyline points="${trail}" fill="none" stroke="${systemColors[s.system]}" opacity=".35" stroke-dasharray="2 4"/><circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${used?7:5}" fill="${systemColors[s.system]}" opacity="${s.cn0===null?.35:1}"/><text x="${(x+9).toFixed(1)}" y="${(y+4).toFixed(1)}">${s.id}</text>`;}).join('');
 $('spectrum').innerHTML=sats.length?sats.map(s=>`<div class="signalrow"><span style="color:${systemColors[s.system]}">${s.id}</span><span class="signaltrack"><span class="signalbar" style="width:${Math.min(100,(s.cn0??0)/60*100)}%;background:${systemColors[s.system]}"></span></span><span>${s.cn0===null?'—':s.cn0}</span></div>`).join(''):'<p>No satellite signal measurements yet.</p>';
}
function parseNmea(line){const match=line.match(/^\$([A-Z]{2})([A-Z]{3}),(.*)\*([0-9A-F]{2})$/i);if(!match)return false;let checksum=0;for(const c of line.slice(1,line.indexOf('*')))checksum^=c.charCodeAt(0);if(checksum!==parseInt(match[4],16)){log('Ignored NMEA sentence with invalid checksum');return false;}
 const [,talker,type,body]=match,p=[talker+type,...body.split(',')];nmea.seen=true;set('nmeastatus',state.demo?'Simulated NMEA observations':`NMEA received ${new Date().toLocaleTimeString()} · older satellite readings expire after 15 s`);
 if(type==='GSV'){const total=Number(p[1]),part=Number(p[2]);if(!Number.isInteger(total)||total<1||total>32||part<1||part>total)return false;const hasSignal=(p.length-4)%4===1,signal=hasSignal?p.at(-1):'',cycleKey=talker+':'+signal;if(part===1)nmea.cycles.set(cycleKey,{parts:new Map(),time:Date.now(),total});const cycle=nmea.cycles.get(cycleKey);if(!cycle||cycle.total!==total||Date.now()-cycle.time>5000)return false;const list=[];
 for(let i=4;i+3<p.length-(hasSignal?1:0);i+=4){if(!/^\d+$/.test(p[i]))continue;const prn=Number(p[i]),system=satelliteSystem(talker,prn),num=x=>x!==''&&Number.isFinite(Number(x))?Number(x):null;let el=num(p[i+1]),az=num(p[i+2]),cn0=num(p[i+3]);if(el!==null&&(el<0||el>90))el=null;if(az!==null&&(az<0||az>360))az=null;if(cn0!==null&&(cn0<0||cn0>99))cn0=null;list.push({id:satId(system,prn),system,el,az,cn0});}
 cycle.parts.set(part,list);if(cycle.parts.size===total){const all=[...cycle.parts.values()].flat(),ids=new Set(all.map(s=>s.id));for(const [key,s] of nmea.satellites)if(s.source===cycleKey&&!ids.has(key))nmea.satellites.delete(key);for(const s of all){const old=nmea.satellites.get(s.id),trail=old?.trail||[];if(s.el!==null&&s.az!==null){trail.push([s.el,s.az]);if(trail.length>60)trail.shift();}nmea.satellites.set(s.id,{...s,trail,time:Date.now(),source:cycleKey});}nmea.cycles.delete(cycleKey);drawSatellites();}}
 if(type==='GSA'){const systemId=Number(p[18]),system=({1:'GPS',2:'GLONASS',3:'Galileo',4:'BeiDou',5:'QZSS'})[systemId];const ids=new Set(p.slice(3,15).filter(x=>/^\d+$/.test(x)).map(x=>satId(system||satelliteSystem(talker,Number(x)),Number(x))));nmea.used.set(talker+':'+systemId,{ids,time:Date.now()});if(state.gnss.fix)set('dops',p.slice(15,18).map(x=>x||'—').join(' / '));drawSatellites();}
 if(type==='GGA'){const quality=Number(p[6]);if(!quality){clearGnss(state.gnss.power===false?'Receiver off':'Searching · no fix');}else{const names={1:'Standalone GPS',2:'Differential',4:'RTK fixed',5:'RTK float',6:'Estimated'};set('fixquality',`${names[quality]||'Quality '+quality} / ${p[7]||'—'} satellites`);const geoid=Number(p[11]),alt=Number(p[9]);set('geoid',p[11]!==''&&Number.isFinite(geoid)?geoid.toFixed(2)+' m':'—');set('ellipsoid',p[9]!==''&&p[11]!==''&&Number.isFinite(alt+geoid)?(alt+geoid).toFixed(2)+' m':'—');}}
 if(type==='GST'&&state.gnss.fix)set('positionerror',p.slice(6,9).map(x=>x!==''&&Number.isFinite(Number(x))?Number(x).toFixed(2)+' m':'—').join(' / '));updateCourse();return true;
}
async function setupNmea(){try{const prior=await command('AT+CGPSINFOCFG?'),m=prior.match(/\+CGPSINFOCFG:\s*(\d+),(\d+)/);if(!m)throw new Error('NMEA configuration not reported');nmea.previous=[Number(m[1]),Number(m[2])];await command('AT+CGPSINFOCFG=1,198143');nmea.active=true;set('nmeastatus','NMEA streaming enabled · waiting for satellite observations');}catch(e){log(`NMEA streaming unavailable: ${e.message}`);set('nmeastatus','NMEA stream unavailable. Position queries remain available.');}}
function demoNmea(){const sentence=body=>{let x=0;for(const c of body)x^=c.charCodeAt(0);return '$'+body+'*'+x.toString(16).padStart(2,'0').toUpperCase();};for(const [talker,rows] of [['GP',['01,65,030,45','05,40,120,38','12,25,240,32','20,75,310,48']],['GL',['65,50,070,41','72,30,195,35']],['GA',['301,55,160,43','305,15,280,28']],['BD',['201,42,350,39','205,20,100,30']]])parseNmea(sentence(`${talker}GSV,1,1,${rows.length},${rows.join(',')}`));parseNmea(sentence('GPGGA,163000.0,5128.614000,N,00000.030000,W,1,14,1.0,45.0,M,48.0,M,,'));}

// SMS uses PDU mode so a message body cannot be mistaken for an AT response.
const gsmAlphabet=Array.from('@£$¥èéùìòÇ\nØø\rÅåΔ_ΦΓΛΩΠΨΣΘΞ\x1bÆæßÉ !"#¤%&\'()*+,-./0123456789:;<=>?¡ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÑÜ§¿abcdefghijklmnopqrstuvwxyzäöñüà');
const gsmExtension={10:'\f',20:'^',40:'{',41:'}',47:'\\',60:'[',61:'~',62:']',64:'|',101:'€'};
function gsmSeptets(text){const result=[];for(const c of text){const n=gsmAlphabet.indexOf(c);if(n>=0&&n!==27)result.push(n);else{const ext=Object.keys(gsmExtension).find(k=>gsmExtension[k]===c);if(ext===undefined)return null;result.push(27,Number(ext));}}return result;}
function unpackGsm(bytes,count,startBit=0){let text='',escape=false;for(let n=0;n<count;n++){const bit=startBit+n*7,index=bit>>3,shift=bit%8;const v=((bytes[index]>>shift)|((bytes[index+1]||0)<<(8-shift)))&127;if(escape){text+=gsmExtension[v]??'�';escape=false;}else if(v===27)escape=true;else text+=gsmAlphabet[v]??'�';}return text+(escape?'�':'');}
function packGsm(septets){const bytes=new Uint8Array(Math.ceil(septets.length*7/8));septets.forEach((v,n)=>{const bit=n*7,i=bit>>3,shift=bit%8;bytes[i]|=v<<shift;if(i+1<bytes.length)bytes[i+1]|=v>>(8-shift);});return bytes;}
function smsEncoding(text){if(!text)return {valid:false,count:0,limit:160,name:'GSM text',error:'Write a message first.'};const septets=gsmSeptets(text);if(septets)return {valid:septets.length<=160,count:septets.length,limit:160,name:'GSM text',bytes:packGsm(septets),dcs:0,udl:septets.length,error:'This version sends one text at a time: shorten it to 160 GSM characters (some symbols count twice).'};if(/[\uD800-\uDFFF]/.test(text))return {valid:false,count:text.length,limit:70,name:'Unicode',error:'Emoji and characters outside the basic Unicode plane are not supported. Remove them before sending.'};const bytes=new Uint8Array(text.length*2);for(let n=0;n<text.length;n++){bytes[n*2]=text.charCodeAt(n)>>8;bytes[n*2+1]=text.charCodeAt(n)&255;}return {valid:text.length<=70,count:text.length,limit:70,name:'Unicode',bytes,dcs:8,udl:bytes.length,error:'This version sends one Unicode text at a time: shorten it to 70 characters.'};}
function hexBytes(bytes){return Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('').toUpperCase();}
function buildSmsPdu(number,text){number=number.replace(/[ ()-]/g,'');if(!/^\+?\d{1,20}$/.test(number))throw new Error('Enter a phone number or numeric short code, preferably with its country code.');const e=smsEncoding(text);if(!e.valid)throw new Error(e.error);const digits=number.replace(/^\+/,''),semi=(digits.length%2?digits+'F':digits).match(/../g).map(p=>parseInt(p[1]+p[0],16));const bytes=[0,1,0,digits.length,number.startsWith('+')?145:129,...semi,0,e.dcs,e.udl,...e.bytes];return {hex:hexBytes(bytes),length:bytes.length-1,encoding:e.name};}
function decodeUcs2(bytes){if(bytes.length%2)throw new Error('Incomplete Unicode SMS');let result='';for(let n=0;n<bytes.length;n+=2)result+=String.fromCharCode(bytes[n]*256+bytes[n+1]);return result;}
function decodeSmsPdu(hex){if(!/^(?:[0-9a-f]{2})+$/i.test(hex))throw new Error('Invalid SMS PDU');const b=Uint8Array.from(hex.match(/../g),x=>parseInt(x,16));let i=0;const take=n=>{if(i+n>b.length)throw new Error('Truncated SMS PDU');const v=b.slice(i,i+n);i+=n;return v;},byte=()=>take(1)[0];const sc=byte();take(sc);const first=byte(),type=first&3;let address='',timestamp='';if(type===1)byte();else if(type!==0)return {address:'Service report',timestamp:'',text:'Non-text SMS record. Raw data is available in the AT log.',concat:null};const length=byte(),toa=byte(),addressBytes=take(Math.ceil(length/2));if((toa&112)===80)address=unpackGsm(addressBytes,Math.floor(length*4/7));else address=((toa&112)===16?'+':'')+Array.from(addressBytes,x=>(x&15).toString(16)+(x>>4).toString(16)).join('').slice(0,length);byte();const dcs=byte();if((dcs&192)===0&&(dcs&32))throw new Error('Compressed SMS is not supported');if(type===0){const t=take(7),swap=x=>(x&15)*10+(x>>4),v=Array.from(t.slice(0,6),swap),zone=swap(t[6]&247),offset=zone*15;timestamp=`20${String(v[0]).padStart(2,'0')}-${String(v[1]).padStart(2,'0')}-${String(v[2]).padStart(2,'0')} ${v.slice(3).map(x=>String(x).padStart(2,'0')).join(':')} UTC${t[6]&8?'-':'+'}${String(Math.floor(offset/60)).padStart(2,'0')}:${String(offset%60).padStart(2,'0')}`;}else{const vp=(first>>3)&3;if(vp===2)take(1);else if(vp===1||vp===3)take(7);}
 const udl=byte(),alphabet=(dcs&192)===0?(dcs>>2)&3:(dcs&240)===224?2:(dcs&240)===240?(dcs>>2)&1:0,ud=take(alphabet===0?Math.ceil(udl*7/8):udl);let header=0,concat=null;
 if(first&64){header=ud[0]+1;if(header>ud.length)throw new Error('Invalid SMS header');for(let p=1;p+1<header;){const id=ud[p++],len=ud[p++];if(p+len>header)throw new Error('Invalid SMS header element');if(id===0&&len===3)concat={ref:ud[p],total:ud[p+1],part:ud[p+2]};if(id===8&&len===4)concat={ref:ud[p]*256+ud[p+1],total:ud[p+2],part:ud[p+3]};if(id===36||id===37)throw new Error('National-language SMS tables are not supported');p+=len;}}
 let text;if(alphabet===0){const skip=Math.ceil(header*8/7);if(udl<skip)throw new Error('Invalid SMS text length');text=unpackGsm(ud,udl-skip,skip*7);}else if(alphabet===2)text=decodeUcs2(ud.slice(header));else text='Binary message: '+hexBytes(ud.slice(header));return {address,timestamp,text,concat};}
function parseSmsList(response,store){const lines=response.split('\n'),messages=[];for(let n=0;n<lines.length;n++){const m=lines[n].match(/^\+CMGL:\s*(\d+),(\d+),/);if(!m)continue;let raw='';for(let j=n+1;j<lines.length;j++){if(/^\+CMGL:|^OK$/.test(lines[j]))break;if(/^(?:[\da-f]{2})+$/i.test(lines[j])){raw=lines[j];break;}}if(!raw)throw new Error('Message data is missing; refresh before retrying.');let decoded;try{decoded=decodeSmsPdu(raw);}catch(e){decoded={address:'Unsupported message',timestamp:'',text:e.message+' · raw PDU is in the AT log.',concat:null};}messages.push({store,index:Number(m[1]),status:Number(m[2]),raw,...decoded});}return messages;}
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderSms(){set('smsbadge',sms.pending?'NEW TEXT':'SMS');$('smslist').innerHTML=sms.messages.length?sms.messages.map(m=>`<article class="smscard"><header><strong>${escapeHtml(m.address)}</strong><span class="tag">${['Received · unread','Received · read','Draft','Sent'][m.status]||'Stored'}</span><time>${escapeHtml(m.timestamp)}</time></header><pre>${escapeHtml(m.text)}</pre><footer><span>${m.store==='SM'?'SIM':'Modem'} · slot ${m.index}${m.concat?` · part ${m.concat.part} of ${m.concat.total}`:''}${state.demo?' · simulated':''}</span><button class="secondary" data-sms-delete="${m.index}" ${!state.connected||state.busy?'disabled':''}>Delete text</button></footer></article>`).join(''):'<p class="empty">'+(sms.loaded?'No messages in this storage.':'No messages loaded.')+'</p>';}
function updateSmsCount(){const e=smsEncoding($('smsbody').value);set('smscount',`${e.count} / ${e.limit} · ${e.name} · one text${$('smsbody').value&&!e.valid?' · '+e.error:''}`);$('smssend').disabled=!state.connected||state.busy||!e.valid||!/^\+?\d{1,20}$/.test($('smsnumber').value.replace(/[ ()-]/g,''));}
function clearMessaging(){sms.messages=[];sms.loaded=false;sms.pending=false;sms.dirty=new Set();sms.identity=null;sms.receiving=false;sms.previousCnmi=null;ussd.active=false;ussd.pending=false;ussd.buffer='';renderSms();set('smsstatus','Connect USB, then load messages. Reading marks received texts as read.');set('ussdstatus','Ready when connected.');set('ussdresult','No USSD response yet.');set('smssendstatus','One SMS per send. Network acceptance does not confirm delivery.');}
async function checkSmsSim(){const r=await command('AT+CIMI'),m=r.match(/(?:^|\n)(\d{10,16})(?:\n|$)/);if(!m)throw new Error('SIM identity unavailable. Wait for the SIM to be ready.');if(sms.identity&&sms.identity!==m[1]){sms.messages=[];sms.loaded=false;sms.pending=false;sms.dirty.clear();ussd.active=false;set('ussdresult','SIM changed. Previous response cleared.');$('smsbody').value='';$('smsnumber').value='';renderSms();set('smsstatus','SIM changed. Load messages for this card.');sms.identity=m[1];throw new Error('SIM changed. Review the new card before retrying.');}sms.identity=m[1];return m[1];}
async function setupMessaging(){try{await checkSmsSim();const r=await command('AT+CNMI?'),m=r.match(/\+CNMI:\s*([\d, ]+)/);if(!m)throw new Error('New-message settings unavailable');sms.previousCnmi=m[1].split(',').map(Number);await command('AT+CNMI=2,1,0,0,0');sms.receiving=true;set('smsstatus','Listening for incoming texts. Load messages to view existing texts; reading marks them as read.');}catch(e){set('smsstatus','Incoming alerts unavailable. Use Load messages to check manually.');log('SMS setup: '+e.message);}}
async function smsMode(store,fn){const r=await command('AT+CMGF?'),mode=r.match(/\+CMGF:\s*([01])/);if(!mode)throw new Error('SMS mode unavailable');const stores=await command('AT+CPMS?'),old=stores.match(/\+CPMS:\s*"([A-Z]+)"/);if(!old)throw new Error('SMS storage unavailable');try{await command('AT+CMGF=0');if(store)await command(`AT+CPMS="${store}"`);return await fn();}finally{if(state.connected&&!waiter){if(store)await command(`AT+CPMS="${old[1]}"`).catch(e=>log('SMS storage restore: '+e.message));await command(`AT+CMGF=${mode[1]}`).catch(e=>log('SMS mode restore: '+e.message));}}}
async function loadMessages(){if(!state.connected||state.busy)return;const store=$('smsstore').value;if(!['SM','ME'].includes(store))throw new Error('Choose SIM or modem storage');state.busy=true;controls();set('smsstatus','Loading messages…');try{await enqueue(async()=>{await checkSmsSim();sms.messages=await smsMode(store,async()=>parseSmsList(await command('AT+CMGL=4',undefined,20000),store));sms.loaded=true;sms.dirty.delete(store);sms.pending=sms.dirty.size>0;renderSms();});set('smsstatus',`${sms.messages.length} stored text${sms.messages.length===1?'':'s'} · refreshed ${new Date().toLocaleTimeString()}. Received texts are now marked read.${sms.pending?' New texts are also waiting in the other storage.':''}`);}catch(e){set('smsstatus','Could not load messages: '+e.message);throw e;}finally{state.busy=false;controls();renderSms();}}
async function deleteMessage(index){if(!state.connected||state.busy)return;const message=sms.messages.find(m=>m.index===index&&m.store===$('smsstore').value);if(!message)return;if(!window.confirm(`Delete this text from ${message.address}? This permanently removes ${message.store==='SM'?'SIM':'modem'} slot ${index}.`))return;const identity=sms.identity;state.busy=true;controls();try{await enqueue(async()=>{if(await checkSmsSim()!==identity)throw new Error('SIM changed. Load messages again.');await smsMode(message.store,async()=>{const r=await command(`AT+CMGR=${index}`),raw=r.split('\n').find(x=>/^(?:[\da-f]{2})+$/i.test(x));if(raw?.toUpperCase()!==message.raw.toUpperCase())throw new Error('This storage slot has changed. Refresh messages before deleting.');await command(`AT+CMGD=${index},0`);});sms.messages=sms.messages.filter(m=>m!==message);renderSms();});set('smsstatus','Text deleted.');}catch(e){set('smsstatus','Text was not deleted: '+e.message);throw e;}finally{state.busy=false;controls();renderSms();}}
async function sendSms(){if(!state.connected||state.busy)return;const number=$('smsnumber').value,text=$('smsbody').value,pdu=buildSmsPdu(number,text);state.busy=true;controls();set('smssendstatus','Sending…');try{await enqueue(async()=>{await checkSmsSim();await smsMode(null,async()=>{let entering=false,submitted=false;try{entering=true;await command(`AT+CMGS=${pdu.length}`,line=>line==='>',10000);const response=awaitResponse(line=>line==='OK',65000);try{await write(encoder.encode(pdu.hex));submitted=true;await write(new Uint8Array([26]));}catch(e){rejectWait(e);}const r=await response;if(!/\+CMGS:\s*\d+/.test(r))throw new Error('The modem did not confirm message submission');entering=false;set('smssendstatus','Accepted by the network. Delivery is not confirmed.');}catch(e){if(entering&&!submitted&&state.connected){await write(new Uint8Array([27])).catch(()=>{});await new Promise(r=>setTimeout(r,200));}if(/timed out|disconnect|USB/i.test(e.message)){if(state.connected)await disconnect(false);if(submitted)throw new Error('Submission result unknown. Check with the recipient before retrying to avoid sending a duplicate.');} throw e;}});});}catch(e){set('smssendstatus',e.message);throw e;}finally{state.busy=false;controls();}}
function incomingMessage(line){
 const m=line.match(/^\+CMTI:\s*"(SM|ME)",(\d+)/);
 if(m){sms.pending=true;sms.dirty.add(m[1]);set('smsbadge','NEW TEXT');set('smsstatus',`New text arrived in ${m[1]==='SM'?'SIM card':'modem memory'} · slot ${m[2]}. ${sms.loaded&&$('smsauto').checked?'Refreshing when the modem is idle.':'Load that storage to read it.'}`);return true;}
 if(ussd.buffer){ussd.buffer+='\n'+line;if(ussd.buffer.length>65536){ussd.buffer='';set('ussdstatus','USSD response was too long. End the session before retrying.');}else if(/",\s*\d+$/.test(ussd.buffer)){const response=ussd.buffer;ussd.buffer='';handleUssd(response);}return true;}
 if(line.startsWith('+CUSD:')&&line.includes('"')&&!/",\s*\d+$/.test(line)){ussd.buffer=line;return true;}
 if(line.startsWith('+CUSD:')){handleUssd(line);return true;}return false;
}
function handleUssd(line){const m=line.match(/^\+CUSD:\s*([0-5])(?:,\s*"([\s\S]*)"(?:,\s*(\d+))?)?$/);if(!m)return;let text=m[2]??'',dcs=Number(m[3]);try{if((dcs===72||dcs===8||((dcs&240)===64&&((dcs>>2)&3)===2))&&/^(?:[\da-f]{4})+$/i.test(text))text=decodeUcs2(Uint8Array.from(text.match(/../g),x=>parseInt(x,16)));}catch{ text='Could not decode the USSD response.';}ussd.active=m[1]==='1';set('ussdresult',text||['No response text.','Enter a menu reply.','Session ended.','Another USSD session is active.','USSD is not supported by this network.','Network timed out.'][Number(m[1])]);set('ussdstatus',['Complete.','Menu open · enter your reply, or end the session.','Session ended by the network.','Another USSD session is active.','Not supported by this network.','Network timed out.'][Number(m[1])]);if(ussd.pending){clearTimeout(ussd.timeout);ussd.pending=false;ussd.resolve();}controls();}
async function runUssd(cancel=false){if(!state.connected||state.busy)return;const code=$('ussdcode').value.trim();if(!cancel&&!/^[*#\d+]{1,182}$/.test(code))throw new Error('Enter a USSD code such as *100#, or a numeric menu reply.');state.busy=true;controls();try{await enqueue(async()=>{await checkSmsSim();if(cancel){await command('AT+CUSD=2');ussd.active=false;set('ussdstatus','Session ended.');return;}const charset=await command('AT+CSCS?'),cs=charset.match(/\+CSCS:\s*"([A-Z0-9-]+)"/);if(!cs)throw new Error('Modem text encoding unavailable');if(cs[1]!=='IRA')await command('AT+CSCS="IRA"');set('ussdstatus','Waiting for the network…');set('ussdresult','');ussd.buffer='';const reply=new Promise(resolve=>{ussd.pending=true;ussd.resolve=resolve;ussd.timeout=setTimeout(()=>{ussd.pending=false;ussd.active=false;set('ussdstatus','No response within 45 seconds. End the session before retrying.');resolve();},45000);});try{await command(`AT+CUSD=1,"${code}",15`);await reply;}finally{clearTimeout(ussd.timeout);ussd.pending=false;ussd.buffer='';if(state.connected&&cs[1]!=='IRA')await command(`AT+CSCS="${cs[1]}"`).catch(e=>log('Text encoding restore: '+e.message));}});}catch(e){set('ussdstatus','USSD failed: '+e.message);throw e;}finally{state.busy=false;controls();}}
function demoMessages(){sms.messages=[{store:'SM',index:1,status:0,address:'Demo operator',timestamp:'2026-10-01 12:00:00 UTC',text:'Welcome! This is a simulated received text.',raw:'',concat:null}];sms.loaded=true;renderSms();set('smsstatus','Simulated messages · connect USB to read your SIM.');set('ussdresult','Demo balance: 12.50 · valid until 31 December 2026.\nSimulated response, not your account.');set('ussdstatus','Demo · simulated');}
$('smsbody').addEventListener('input',updateSmsCount);$('smsnumber').addEventListener('input',updateSmsCount);$('smsrefresh').addEventListener('click',()=>loadMessages().catch(report));$('smsstore').addEventListener('change',()=>{sms.messages=[];sms.loaded=false;renderSms();set('smsstatus','Load messages from the selected storage.');});$('smsform').addEventListener('submit',e=>{e.preventDefault();sendSms().catch(report);});$('smslist').addEventListener('click',e=>{const button=e.target.closest('[data-sms-delete]');if(button)deleteMessage(Number(button.dataset.smsDelete)).catch(report);});$('ussdform').addEventListener('submit',e=>{e.preventDefault();runUssd().catch(report);});$('ussdcancel').addEventListener('click',()=>runUssd(true).catch(report));

controls();

// ?demo=1 opens straight into simulated readings, e.g. for the hosted copy.
if(globalThis.location&&new URLSearchParams(location.search).get('demo')==='1')demo();
